import 'package:firebase_core/firebase_core.dart';
import 'package:flutter/foundation.dart';

/// Firebase options generated by FlutterFire for configured platforms.
///
/// Web and Android are configured for the Playce MATC89 Firebase project.
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }

    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not configured for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'REMOVED',
    appId: '1:696855005471:web:1642dd1c2c5c426d32082a',
    messagingSenderId: '696855005471',
    projectId: 'playce-matc89-vinic',
    authDomain: 'playce-matc89-vinic.firebaseapp.com',
    storageBucket: 'playce-matc89-vinic.firebasestorage.app',
    measurementId: 'G-YX9VR37GT7',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'REMOVED',
    appId: '1:696855005471:android:be89d110376fdbc932082a',
    messagingSenderId: '696855005471',
    projectId: 'playce-matc89-vinic',
    storageBucket: 'playce-matc89-vinic.firebasestorage.app',
  );
  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'REPLACE_ME',
    appId: 'REPLACE_ME',
    messagingSenderId: 'REPLACE_ME',
    projectId: 'REPLACE_ME',
    iosBundleId: 'com.example.atividadeFlutter',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'REPLACE_ME',
    appId: 'REPLACE_ME',
    messagingSenderId: 'REPLACE_ME',
    projectId: 'REPLACE_ME',
    iosBundleId: 'com.example.atividadeFlutter',
  );
}
