name: design_system
description: Playce design tokens and reusable UI components.
publish_to: 'none'

environment:
  sdk: ^3.9.2

dependencies:
  flutter:
    sdk: flutter
  google_fonts: ^6.2.1

dev_dependencies:
  flutter_lints: ^5.0.0
  flutter_test:
    sdk: flutter
